# Trading Bot Configuration

# General settings
account:
  equity: 1000.0  # Starting account equity
  max_daily_loss_pct: 2.0 # Max percentage of equity to lose in a day

# Risk management settings
risk:
  default_per_trade_risk_pct: 1.0 # Default risk per trade as a percentage of equity
  max_open_positions: 5 # Max number of concurrent open trades
  max_daily_drawdown_pct: 2.0 # Max percentage of equity to lose in a day before halting

# Instruments to trade
instruments:
  - "SPY" # S&P 500 ETF
  - "QQQ" # Nasdaq 100 ETF

# Pattern and signal settings
patterns:
  # Feature flags to enable/disable patterns
  enable_double_top_bottom: true
  enable_engulfing: true
  enable_abcd: true

  # Confluence score threshold
  min_confluence_score: 60 # Minimum score (0-100) to consider a signal valid

  # Tolerances for pattern recognition
  double_top_bottom:
    price_similarity_threshold: 0.01 # Max 1% difference between the two tops/bottoms
    neckline_break_confirmation: 0.005 # Price must move 0.5% beyond neckline
  abcd:
    price_symmetry_tolerance: 0.15 # Allow 15% deviation between AB and CD legs
    time_symmetry_tolerance: 0.25 # Allow 25% deviation in time
  gartley:
    b_point_tolerance: 0.05 # 5% tolerance around the 0.618 XA retracement
    d_point_tolerance: 0.05 # 5% tolerance around the 0.786 XA retracement

# Execution settings
execution:
  broker: "paper" # "paper", "interactive_brokers", "binance"
  slippage_pct: 0.001 # 0.1% slippage assumption for backtesting
  commission_per_trade: 1.0 # Fixed commission per trade in USD
